[package]
name = "testing"
version = "0.1.0"
edition = "2021"

[toolchain]
channel = "nightly"
targets = ["wasm32-unknown-unknown"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
